{% set name = "electron" %}
{% set version = "4.0.0-nightly.20180817" %}
{% set sha256 = "c5a19e49ec98598a0b21de51ee97e891ec6651a74ffd57e940d523f80e899fef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/electron/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g electron
  requires:
    - nodejs
   
about:
  home: https://github.com/electron/electron
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Build cross platform desktop apps with JavaScript, HTML, and CSS'
  description: |
    Build cross platform desktop apps with JavaScript, HTML, and CSS 
  doc_url: https://electron.atom.io/
  dev_url: https://github.com/electron/electron

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
