{% set name = "electron" %}
{% set version = "1.8.4" %}
{% set sha256 = "b8fd5f2544eb8ca4d96ef5ee5311caf1af33f9c403be2f43107af0ae679c6d90" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/electron/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g electron
  requires:
    - nodejs
   
about:
  home: https://github.com/electron/electron
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Build cross platform desktop apps with JavaScript, HTML, and CSS'
  description: |
    Build cross platform desktop apps with JavaScript, HTML, and CSS 
  doc_url: https://electron.atom.io/
  dev_url: https://github.com/electron/electron

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
