travis:
  secure:
    BINSTAR_TOKEN: dwFtuRNFxA9/Tx4gP/Lw0ov5WHJT1gOP0gBPCpiVc05decMXF5Dgj++IXO+Ce4ueMluFB3PNze3RKhxboGPxCME7iO8b/PvHYnQWmSjIIJcsjv9gZzkwAI+VhCYsHwhl+fhpC3VaR0UfmeMcx2Bm5MjJE8VI2hLRNTH7O8uPUG/wDUqXpOmtFyLQhEWXZbiZ/3ecrsQtljkysx4JSTDPPkmrJlWlSLcWqi0nvn8rwdJ//WVT73dUF23Um7cyEI5Pqx4BgBvVyhsB6MoGUqPI8e6NwG/qbhaQ3GO+UeZTlx+I+Aa0+xlU/Ndp08DvOejzNFA7S4iRgwUpRdELnFNyohEHc/4WeckhRRO4ztBmTefmD2Qc+AouhR6hmxpRjANOv/0JwQ983iQtcRtBS1MEMXeXPdjz+f276yP0LCBr/Zmnr4vFlDS2FMz9TOyGF4tt4RsiAru7MueTblfpfiYsfKEtz/VO86he7jD4Qt1kmED5edstoK2u3XB2XSI6f7QQGh0rKGpr+4sB41hh3cWLVbJy4mx34urZZvshQ9+MhWHAML403QyT9Ot6eGG8frdjqhWFAsS6HMsPUo4pmZuICR1lGFipwQEsIsKXrJ7aOE9VR4YOlQ9p6YD7wS+LDKate7maJa9G17K5APtUpNJPYS+S2ZfBCwp8LFTJz8Z2Se4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
