travis:
  secure:
    BINSTAR_TOKEN: oEYz18R4+ybVmxsFFSVfwWxHbx11mTQ4xWo1qC6sZbNu1APomJDWUE3zu7KNjxqDXan0AeQqjAe0bp97nsxudNHnKb+6CPaEXT0aGXSdFNBRfsJ9HBsTliLDAXSAIKRvRizSmk1iB8ygcorwaVv/5ErouL2eZlUHSYuFGM+E4xZsObZstCyCQ3Vn/wfEVBC/Hlw9oh/Ue+hwXSli6y9yh+NKP4L/5Bn9+3eHgMJetkZGJOP+o8CH5v0g+86rZlUlfLRn5jUpOjIfE9KIG14DZ7LSBZur4yeN4OSbvaY3kagOEpM98G575Ctdl3EnCQ3T8Od97W1D5tHJ2xn674x+bK2Qnvc6076a8yHbvQ5vwJLF5TuyHax27knYYGId2eRvShETq0lF4sJEk3Lf9CgZZSsXPUhX7JHyTx6quqYBIiQnZveZyKe925JxBoA313oL14g/LWZLx0oDSFpXeUvoHYsc7buT3y31y1hdYvB4wXT1fyNahu+E/jX2GclTWmlm7J0VVuJrWXbOMdbVc5b9uALiYNPE8jWfqHVmQgKKR2Q4aXZobtmLMdfK2D5+CHLKPlF1pyYaA2Rm+vSZv+mPKeEPy6P0KzSIHuLbIWDuxM2imG3yS42NJW3lf5aGRG+4senq7Gbh+Y2VeOFcrsYv8xfXUhX09X+dRQdQLKsjdGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
