travis:
  secure:
    BINSTAR_TOKEN: TlpRHWwWwXn1LV1s1deZ6E5EcNsByxroJ1pJPLsCkVs2LxM8Z35aSETayaXvXM9Br2rvefwLfu1PEHAXm6LhS774+jYja+RczydCodVlGjMpBqjTBEs0YLv3CNjElBEINhorzA0OCkc7sCLSDK295OU5aw4f4KvPNBU32+YocIt3eH7xf+RwApPRo8HOpQ4acAPFhqQWwpVNoabJ16M1uY9f2T+af7fg7KDiS3vpcl1VuUzWpYO6q74chqPWnytTPc8ZIVf7UiIWPn7WTPKrC+4KeYRtgxrBr3cm5cQDQb38ixnouHyq9ISbzpsS14xwdcIm1WjFi7r3ZZlOAlz/p0SzLzqZtd3k1GRDajwAX/UVz3dBHBDK/YT5pd2RSbWXcE6msOOMjxheAINily9YLjMzf1bXu83VeTY2nvXuMjkPkJ670Ignk5/0wzwj6ephMrFHFXGgmx/CXyBX4lB72/H3iCvej+yUxPso1wCVqAn8OIxBPy0NYROVXWezOO7n8FeamtAO5yj4JcDGPt8oSO/p1OEnIJ/Otn0xlrqMR1VWnHBwLLwb4zMiafNbU6qAUOzT1BB46oQ7CiBk3Zlfw0sMR3yI+7fawmPqNb0HBNxIvEUBAEZbECOcvlxo8ppps60PXWdnTY0QMZEarShCcVRPeCPufRT9sJC5UM6uRWk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
