travis:
  secure:
    BINSTAR_TOKEN: xXkkte8SFnU/3UmlcdfADaJf6pAIH9Qj1ZQbGoNg5YZqrHDgy3QNNdDDb1kxoZR8BIQSGrLUhjGZkgDyZea69d0YZxxyGoGsJt9fNcniy/fnNqjpguLhtWGZGOJRkEDYrvUNQ77q4Sn041Kd+g7jythxvl8eBpvH1hVZq3b7tbGsOrFe0qPkVvIO/ObE2YfTYKOOdZ1hcO5TtXwlbVPULaJYULPU5TPVQMVeqalRCfNWmjnxzovt7UJ73G9oOm9tag5Yb9c7P5JySPaFw4tRAb6fl1ATW7JeSGUY1VWIRnkKrIWi1KzoxUAG6o1QHtQEhXCQXVxHuAHAH62aMyq770bE2CdYcjDzJ1E4FZjUd/KzLHbJvBhEzl7PGRkDU7zmRiy7vYTb+MUXIzbS0F1/ntKhRLP41y1ScvQubK3m2E0A4ezwwPMqq9weNES0j7rsLmROcrJMUK7F0nTJtgqQb1VlfL4OuZw84WRLbAdTGbOOLswfEVKl6fT/wL4pHmKIgrfXUI7q+fLaPWi7n86ae1mBDalIoCJyKyfuuerz5TefSSEYN+exOfCrXosJ6OnjtmYvaHCROs3Ka+SqrmxVLbBjXfxeH+wKYiuIKGpqGrfMooMPfD9aL5ZyV4jJX44Bd0Q0qCrSr2ouQwxmsLeX3PDNHvtDKXEyjzcJZA8x2b4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
